# Generated by Django 5.1.1 on 2024-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_media_delete_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feeling',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprised', 'Surprised'), ('love', 'Love'), ('thankful', 'Thankful'), ('confused', 'Confused'), ('excited', 'Excited'), ('calm', 'Calm'), ('none', 'None')], default='happy', max_length=50),
        ),
    ]
