# Generated by Django 5.1.1 on 2024-10-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_feeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
