# Generated by Django 5.1.1 on 2024-10-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_visibility_selectedfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='post.post'),
        ),
    ]
