# Generated by Django 5.1.1 on 2024-10-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='active_call',
            field=models.BooleanField(default=False),
        ),
    ]
