# Generated by Django 5.1.1 on 2024-10-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_active_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={},
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='timestamp',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='call_type',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='caller',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='receiver',
        ),
        migrations.AddField(
            model_name='calllog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='started_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calls_started', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calllog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat.chatroom'),
        ),
    ]
