# Generated by Django 5.1.1 on 2024-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_calllog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='started_by',
        ),
        migrations.AddField(
            model_name='calllog',
            name='caller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caller_logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('ended', 'Ended')], default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='chat.chatroom'),
        ),
    ]
