# Generated by Django 5.1.1 on 2024-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_calllog_started_by_calllog_caller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
