# Generated by Django 5.1.1 on 2024-10-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_calllog_agora_channel_alter_calllog_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
