# Generated by Django 5.1.1 on 2024-10-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendship_online_alter_friendship_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='online',
        ),
    ]
